/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_port_app;

import java.awt.Component;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author WStevens
 */
public class CycleCountReport extends javax.swing.JFrame {

    /**
     * @return the formHeader
     */
    public String getFormHeader() {
        return formHeader;
    }

    /**
     * @param aFormHeader the formHeader to set
     */
    public void setFormHeader(String aFormHeader) {
        formHeader = aFormHeader;
    }
    
    private Connection conn = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    private String formHeader = null;
    private Component frame;
    /**
     * Creates new form StoreReports
     */
    public CycleCountReport() {
      //  Test_Label.setVisible(false);
        String[] args = null;
        GtDates.main(args);
        initComponents();
        conn = DBConnect.connection;
        GetCycleCountReports();
        formHeader = GtDates.tdate;
        Cycle_Count_Table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        Cycle_Count_Table.getColumnModel().getColumn(0).setPreferredWidth(215);        
      //  Cycle_Count_Table.getColumnModel().getColumn(1).setPreferredWidth(40);
        Cycle_Count_Table.getColumnModel().getColumn(1).setPreferredWidth(60);
        Cycle_Count_Table.getColumnModel().getColumn(2).setPreferredWidth(40);
        Cycle_Count_Table.getColumnModel().getColumn(3).setPreferredWidth(40);
        Cycle_Count_Table.getColumnModel().getColumn(4).setPreferredWidth(180);
        Cycle_Count_Table.getColumnModel().getColumn(5).setPreferredWidth(60);
        Cycle_Count_Table.getColumnModel().getColumn(6).setPreferredWidth(40);
        Cycle_Count_Table.getColumnModel().getColumn(7).setPreferredWidth(40);        
        Cycle_Count_Table.getColumnModel().getColumn(8).setPreferredWidth(180);
        Cycle_Count_Table.getColumnModel().getColumn(0).setHeaderValue("Form_Names");        
     //   Cycle_Count_Table.getColumnModel().getColumn(1).setHeaderValue("Lines");
        Cycle_Count_Table.getColumnModel().getColumn(1).setHeaderValue("Sku in Inv");
        Cycle_Count_Table.getColumnModel().getColumn(2).setHeaderValue("Qty in Inv");
        Cycle_Count_Table.getColumnModel().getColumn(3).setHeaderValue("DCS for Sku in Inv");
        Cycle_Count_Table.getColumnModel().getColumn(4).setHeaderValue("Desc of Sku in Inv");
        Cycle_Count_Table.getColumnModel().getColumn(5).setHeaderValue("Sku Change");
        Cycle_Count_Table.getColumnModel().getColumn(6).setHeaderValue("Qty Change");
        Cycle_Count_Table.getColumnModel().getColumn(7).setHeaderValue("DCS for Sku Change");
        Cycle_Count_Table.getColumnModel().getColumn(8).setHeaderValue("Desc of Sku Change");
    }
    // gets data from database and puts it in table
    private void GetCycleCountReports() {
        try  {
    String sql = "SELECT Form_Name, Sku, Qty, First_DCS, Description1, New_Sku, Qty_In, Second_DCS, Description2 FROM cyclecountreport";
            setPst(getConn().prepareStatement(sql));
            setRs(getPst().executeQuery());
    Cycle_Count_Table.setModel(DbUtils.resultSetToTableModel(getRs()));
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, e);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    /**
     * Creates new form CycleCountReport
     */
    //public CycleCountReport() {
     //   initComponents();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  //  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Cycle_Count_Table = new javax.swing.JTable();
        Print_Btn = new javax.swing.JButton();
        Close_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cycle_Count_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Cycle_Count_Table);

        Print_Btn.setBackground(new java.awt.Color(255, 255, 0));
        Print_Btn.setText("Print");
        Print_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_BtnActionPerformed(evt);
            }
        });

        Close_Btn.setBackground(new java.awt.Color(255, 0, 0));
        Close_Btn.setText("Close");
        Close_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_BtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Cycle Count Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Print_Btn)
                        .addGap(92, 92, 92)
                        .addComponent(Close_Btn)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_Btn)
                    .addComponent(Close_Btn))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Print_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_BtnActionPerformed
       PrinterJob job = PrinterJob.getPrinterJob();
    PageFormat pf = job.defaultPage();
    Paper paper = pf.getPaper();
  //  double margin = 20.;
    paper.setImageableArea(30, 10, 570, 820);
    
    System.out.println("Printing Form");
    JOptionPane.showMessageDialog(frame, "Form is Printing\nPlease Wait");
    /*
    paper.setImageableArea(margin, 
        paper.getImageableY(),
        paper.getWidth() - 2* margin, paper.getImageableHeight());
    */ 
    pf.setPaper(paper);
    
        MessageFormat header = new MessageFormat("Cycle Count Report  "+ getFormHeader());
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        pf.setOrientation(PageFormat.LANDSCAPE);
        
    job.setPrintable(Cycle_Count_Table.getPrintable(JTable.PrintMode.FIT_WIDTH, header, footer),
            
        job.validatePage(pf));
        try {
            job.print();
            
        } catch (PrinterException ex) {
            Logger.getLogger(PrintForms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Print_BtnActionPerformed

    private void Close_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_BtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_Close_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CycleCountReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CycleCountReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CycleCountReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CycleCountReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CycleCountReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Close_Btn;
    protected javax.swing.JTable Cycle_Count_Table;
    protected javax.swing.JButton Print_Btn;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pst
     */
    public PreparedStatement getPst() {
        return pst;
    }

    /**
     * @param pst the pst to set
     */
    public void setPst(PreparedStatement pst) {
        this.pst = pst;
    }

    /**
     * @return the rs
     */
    public ResultSet getRs() {
        return rs;
    }

    /**
     * @param rs the rs to set
     */
    public void setRs(ResultSet rs) {
        this.rs = rs;
    }

    /**
     * @return the conn
     */
    public Connection getConn() {
        return conn;
    }

    /**
     * @param conn the conn to set
     */
    public void setConn(Connection conn) {
        this.conn = conn;
    }
}
