/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form_port_app;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SSwisher & WStevens
 */

// this class is the first window the user sees along with program notes
// the user only needs to click on the inventory adjustment system
public class MainGUI extends GetForms {
    
    private Component frame;
    protected String frmNmI;
    protected String frmNmP;
    protected String frmNmA;
    public ArrayList<String> inPArray = new ArrayList<>();
    public ArrayList<String> pendArray = new ArrayList<>();
    public ArrayList<String> apprArray = new ArrayList<>();
    

    public static DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {

        String[] args = null;
        // attach to button to make program notes optional viewing
       // Notes.main(args);
        initComponents();
        AdminLink.setVisible(false);        
        Store_Number_Label.setText("(" + GtStore.store + ")");
        if (DBConnect.TestEnviron == true) {
            Test_Label.setVisible(true);
        } else if (DBConnect.TestEnviron == false){
            Test_Label.setVisible(false);
        }
        System.out.println("MainGui Opened");
        VersionLabel.setText("Version " + DBConnect.Version);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FormList = new javax.swing.JList(listModel);
        IconLabel = new javax.swing.JLabel();
        StoreLabel = new javax.swing.JLabel();
        AdminLink = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        VersionLabel = new javax.swing.JLabel();
        Bike_Image = new javax.swing.JLabel();
        Test_Label = new javax.swing.JLabel();
        Notes_Btn = new javax.swing.JButton();
        Store_Number_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inventory Adjustment Application Main");
        setBounds(new java.awt.Rectangle(200, 20, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 530));

        Title.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        Title.setText("Inventory Adjustments");

        FormList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Double Click or Select & Press \"ENTER\" :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cordia New", 0, 18))); // NOI18N
        FormList.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FormList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FormListMouseEntered(evt);
            }
        });
        FormList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FormListKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(FormList);

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cglogo2.jpg"))); // NOI18N
        IconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconLabelMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IconLabelMousePressed(evt);
            }
        });

        StoreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StoreLabel.setText("Store #:");

        AdminLink.setForeground(new java.awt.Color(0, 204, 0));
        AdminLink.setText("Admin Link ");
        AdminLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminLinkMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminLinkMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 0, 0));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        VersionLabel.setText("Version 1.109");

        Bike_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guy on bike.jpg"))); // NOI18N
        Bike_Image.setRequestFocusEnabled(false);

        Test_Label.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        Test_Label.setText("(Test Environment)");

        Notes_Btn.setBackground(new java.awt.Color(255, 255, 0));
        Notes_Btn.setText("Notes");
        Notes_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notes_BtnActionPerformed(evt);
            }
        });

        Store_Number_Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Store_Number_Label.setForeground(new java.awt.Color(0, 0, 204));
        Store_Number_Label.setText("52");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*Updated*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Notes_Btn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Bike_Image))
                            .addComponent(jLabel1))
                        .addGap(126, 126, 126))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StoreLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Store_Number_Label)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Test_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VersionLabel)
                    .addComponent(AdminLink))
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AdminLink)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Test_Label)
                                .addGap(31, 31, 31)
                                .addComponent(Title)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StoreLabel)
                            .addComponent(Store_Number_Label)))
                    .addComponent(IconLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Bike_Image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Notes_Btn)
                            .addComponent(exitBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FormListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FormListMouseClicked
        if (evt.getClickCount() == 2) {
            String getValue = FormList.getSelectedValuesList().toString();
            GetForms.formN = getValue.substring(1, getValue.length() - 1);
            if ("Inventory Adjustment System".equals(GetForms.formN)) {
                String[] args = null;
                InvAdj.main(args);            
            } else if ("GO BACK".equals(GetForms.formN)) {
                listModel.removeAllElements();
                GetForms.fSwitch = 0;
                String[] args = null;
                GetForms.mainGbck(args);
            } else if (GetForms.fSwitch == 1) {
                GetForms.GtStoreForm();
            } else if (GetForms.fSwitch == 2) {
                GetForms.GtAdminForm();
            } else {
                GetForms.GtForm();
            }
        }
        
    }//GEN-LAST:event_FormListMouseClicked

    private void FormListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FormListMouseEntered
        FormList.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_FormListMouseEntered

    private void FormListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormListKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String getValue = FormList.getSelectedValuesList().toString();
            GetForms.formN = getValue.substring(1, getValue.length() - 1);
            if ("Inventory Adjustment System".equals(GetForms.formN)) {
                String[] args = null;
                InvAdj.main(args);
            } else if ("GO BACK".equals(GetForms.formN)) {
                listModel.removeAllElements();
                GetForms.fSwitch = 0;
                String[] args = null;
                GetForms.mainGbck(args);
            } else if (GetForms.fSwitch == 1) {
                GetForms.GtStoreForm();
            } else if (GetForms.fSwitch == 2) {
                GetForms.GtAdminForm();
            } else {
                GetForms.GtForm();
            }
        }   
    }//GEN-LAST:event_FormListKeyPressed

    private void IconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconLabelMouseEntered
        IconLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_IconLabelMouseEntered

    private void IconLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconLabelMousePressed
        if (GetForms.fSwitch > 0) {
            listModel.removeAllElements();
            GetForms.fSwitch = 0;
            String[] args = null;
            GetForms.mainGbck(args);
        }
    }//GEN-LAST:event_IconLabelMousePressed

    private void AdminLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLinkMouseEntered
        AdminLink.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_AdminLinkMouseEntered

    private void AdminLinkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLinkMousePressed
        GetForms.fSwitch = 2;
        listModel.removeAllElements();
        String[] args = null;
        GetForms.mainAd(args);
    }//GEN-LAST:event_AdminLinkMousePressed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        GetForms.FrmExt();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        GetForms.FrmExt();
    }//GEN-LAST:event_formWindowClosing

    private void Notes_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notes_BtnActionPerformed
        String[] args = null;
        Notes.main(args);
    }//GEN-LAST:event_Notes_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLink;
    private javax.swing.JLabel Bike_Image;
    public static javax.swing.JList FormList;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JButton Notes_Btn;
    private javax.swing.JLabel StoreLabel;
    private javax.swing.JLabel Store_Number_Label;
    private javax.swing.JLabel Test_Label;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel VersionLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
