/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form_port_app;

import java.awt.Component;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author WStevens
 */


// This class gets line data from the database in inserts it into JTable for the Store to view and print
public class StoreReports extends javax.swing.JFrame {

    /**
     * @return the formHeader
     */
    public static String getFormHeader() {
        return formHeader;
    }

    /**
     * @param aFormHeader the formHeader to set
     */
    public static void setFormHeader(String aFormHeader) {
        formHeader = aFormHeader;
    }

    private Connection conn = null;
    private ResultSet rs = null;
    private PreparedStatement pst = null;
    private static String formHeader = null;
    private Component frame;
    /**
     * Creates new form StoreReports
     */
    public StoreReports() {
      //  Test_Label.setVisible(false);
        String[] args = null;
        GtDates.main(args);
        initComponents();
        conn = DBConnect.connection;
        GetStoreReports();
        formHeader = GtDates.tdate;
        Store_Reports_Table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        Store_Reports_Table.getColumnModel().getColumn(0).setPreferredWidth(215);
       // Store_Reports_Table.getColumnModel().getColumn(1).setPreferredWidth(50);
        Store_Reports_Table.getColumnModel().getColumn(1).setPreferredWidth(70);
        Store_Reports_Table.getColumnModel().getColumn(2).setPreferredWidth(30);
        Store_Reports_Table.getColumnModel().getColumn(3).setPreferredWidth(180);
        Store_Reports_Table.getColumnModel().getColumn(4).setPreferredWidth(200);
        Store_Reports_Table.getColumnModel().getColumn(5).setPreferredWidth(70);
        Store_Reports_Table.getColumnModel().getColumn(6).setPreferredWidth(50);
        Store_Reports_Table.getColumnModel().getColumn(0).setHeaderValue("Form_Names");
      // Store_Reports_Table.getColumnModel().getColumn(1).setHeaderValue("Lines");
        Store_Reports_Table.getColumnModel().getColumn(1).setHeaderValue("Sku in Inv");
        Store_Reports_Table.getColumnModel().getColumn(2).setHeaderValue("Qty");
        Store_Reports_Table.getColumnModel().getColumn(3).setHeaderValue("Desc of Sku in Inv");
        Store_Reports_Table.getColumnModel().getColumn(4).setHeaderValue("Desc of Sku Inv Change");
        Store_Reports_Table.getColumnModel().getColumn(5).setHeaderValue("Attribute");
        Store_Reports_Table.getColumnModel().getColumn(6).setHeaderValue("Size");
    }
    // gets data from database and puts it in table
    private void GetStoreReports() {
        try  {
    String sql = "SELECT Form_Name, Sku, Qty, Description1, Description2, Attribute2, Size2 FROM storeunprocessed";
            setPst(getConn().prepareStatement(sql));
            setRs(getPst().executeQuery());
    Store_Reports_Table.setModel(DbUtils.resultSetToTableModel(getRs()));
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, e);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Store_Reports_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Print_Button = new javax.swing.JButton();
        Close_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Store Reports");

        Store_Reports_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Form_Name", "Line", "Sku", "Qty", "Description1", "Description2", "Attribute2", "Size2"
            }
        ));
        jScrollPane1.setViewportView(Store_Reports_Table);

        jLabel1.setText("Physical Inventory Report");

        Print_Button.setBackground(new java.awt.Color(255, 255, 0));
        Print_Button.setText("Print");
        Print_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_ButtonActionPerformed(evt);
            }
        });

        Close_Btn.setBackground(new java.awt.Color(255, 0, 0));
        Close_Btn.setText("Close");
        Close_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Print_Button)
                        .addGap(115, 115, 115)
                        .addComponent(Close_Btn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Print_Button)
                    .addComponent(Close_Btn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Close_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_BtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_Close_BtnActionPerformed

    // brings up printing prompt for user
    private void Print_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_ButtonActionPerformed
        /* MessageFormat header = new MessageFormat("Store Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
          Store_Reports_Table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
           } catch (java.awt.print.PrinterException e) {
          System.err.format("Failed to Print", e.getMessage());
      }*/ 
        
    PrinterJob job = PrinterJob.getPrinterJob();
    PageFormat pf = job.defaultPage();
    Paper paper = pf.getPaper();
  //  double margin = 20.;
    paper.setImageableArea(30, 10, 570, 820);
    
    System.out.println("Printing Form");
    JOptionPane.showMessageDialog(frame, "Form is Printing\nPlease Wait");
    /*
    paper.setImageableArea(margin, 
        paper.getImageableY(),
        paper.getWidth() - 2* margin, paper.getImageableHeight());
    */ 
    pf.setPaper(paper);
    
        MessageFormat header = new MessageFormat("Physical Inventory Report  "+ getFormHeader());
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        pf.setOrientation(PageFormat.PORTRAIT);
        
    job.setPrintable(Store_Reports_Table.getPrintable(JTable.PrintMode.FIT_WIDTH, header, footer),
            
        job.validatePage(pf));
        try {
            job.print();
            
        } catch (PrinterException ex) {
            Logger.getLogger(PrintForms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Print_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StoreReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StoreReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StoreReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StoreReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StoreReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_Btn;
    private javax.swing.JButton Print_Button;
    private javax.swing.JTable Store_Reports_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the conn
     */
    public Connection getConn() {
        return conn;
    }

    /**
     * @param conn the conn to set
     */
    public void setConn(Connection conn) {
        this.conn = conn;
    }

    /**
     * @return the pst
     */
    public PreparedStatement getPst() {
        return pst;
    }

    /**
     * @param pst the pst to set
     */
    public void setPst(PreparedStatement pst) {
        this.pst = pst;
    }

    /**
     * @return the rs
     */
    public ResultSet getRs() {
        return rs;
    }

    /**
     * @param rs the rs to set
     */
    public void setRs(ResultSet rs) {
        this.rs = rs;
    }
}
