/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form_port_app;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seven_User
 */
public class ViewComplete extends javax.swing.JFrame {

    private Component frame;
    public static int cnt;
    public static int cntPending;
    public static String proc;
    public static String[] recLine = new String[5000];
    public static String[] pending = new String[5000];

    /**
     * Creates new form IAS
     */
    public ViewComplete() {
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
        String[] args = null;
        GtDates.main(args);
        try {
            fTable();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ViewComplete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        exBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        iasBtn = new javax.swing.JButton();
        ebasBtn = new javax.swing.JButton();
        nebasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1108, 605));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(153, 180, 209));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1160, 630));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        exBtn.setText("Export");
        exBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Close");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Store","Qty", "SKU#", "Vendor", "Description", "Reason", "Desc_Damage", "Orig Retail", "New SKU", "Description", "Qty In"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inventory Adjustment (View All Completed)");

        iasBtn.setText("IAS");

        ebasBtn.setText("EBAS");

        nebasBtn.setText("NEBAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exBtn)
                        .addGap(45, 45, 45)
                        .addComponent(exitBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nebasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ebasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exBtn)
                            .addComponent(exitBtn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(iasBtn)
                        .addGap(18, 18, 18)
                        .addComponent(ebasBtn)
                        .addGap(18, 18, 18)
                        .addComponent(nebasBtn)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBtnActionPerformed
        JOptionPane.showMessageDialog(frame, "Form Has Been Exported In '.csv' Format");
        this.dispose();
    }//GEN-LAST:event_exBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewComplete().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ebasBtn;
    private javax.swing.JButton exBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton iasBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton nebasBtn;
    // End of variables declaration//GEN-END:variables

    //Fill Table
    public static void fTable() throws ClassNotFoundException, SQLException {

        cnt = 0;
        cntPending = 0;

        GtStore.GtStore();
        try (Statement s1 = DBConnect.connection.createStatement()) {
            String selTable01 = "SELECT Store AS str, Form_Name As frm FROM existing_forms WHERE Status = 'Pending'";
            s1.execute(selTable01);
            try (ResultSet rs01 = s1.getResultSet()) {
                while (rs01.next()) {
                    cntPending = cntPending + 1;
                    String st = rs01.getString("str");
                    String fr = rs01.getString("frm");
                    pending[cntPending] = st + ";" + fr;
                    //recLine[w] = qty + ";" + sku + ";" + vend + ";" + descr1 + ";" + reas + ";" + ddamg + ";" + orgrt + ";" + nwSku + ";" + descr2 + ";" + qty2 + ";" + lndate;
                }
            }
            
            for (int y = 1; y < cntPending + 1; y++) {
                String str = pending[y].split(";")[0];
                String frm = pending[y].split(";")[1];
                
                // Get Record Count
                String selTable1 = "SELECT COUNT(*) AS total FROM " + frm;
                s1.execute(selTable1);
                try (ResultSet rs1 = s1.getResultSet()) {
                    rs1.next();
                    cnt = rs1.getInt("total");
                }
                
                for (int w = 1; w < cnt + 1; w++) {
                    String selTable3 = "SELECT Sku AS rslt, Qty As rslt2, Description1 As rslt3, "
                            + "Reason As rslt4, Desc_Damage As rslt5, Orig_Retail As rslt6, "
                            + "New_SKU As rslt7, Description2 As rslt8, Qty_In As rslt9, Ln_Date As rslt10 "
                            + "FROM " + frm + " WHERE Line = " + w;
                    s1.execute(selTable3);
                    String qty;
                    String sku;
                    String descr1;
                    String reas;
                    String ddamg;
                    String orgrt;
                    String nwSku;
                    String descr2;
                    String qty2;
                    String lndate;
                    try (ResultSet rs3 = s1.getResultSet()) {
                        rs3.next();
                        qty = rs3.getString("rslt");
                        sku = rs3.getString("rslt2");                        
                        descr1 = rs3.getString("rslt3");
                        reas = rs3.getString("rslt4");
                        ddamg = rs3.getString("rslt5");
                        orgrt = rs3.getString("rslt6");
                        nwSku = rs3.getString("rslt7");
                        descr2 = rs3.getString("rslt8");
                        qty2 = rs3.getString("rslt9");
                        lndate = rs3.getString("rslt10");
                    }
                    
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{GtStore.store, qty, sku, descr1, reas, ddamg, orgrt, nwSku, descr2, qty2, lndate});
                    //recLine[w] = qty + ";" + sku + ";" + vend + ";" + descr1 + ";" + reas + ";" + ddamg + ";" + orgrt + ";" + nwSku + ";" + descr2 + ";" + qty2 + ";" + lndate;
                }
            }
        }
    }
}